# development stage
FROM node:lts-alpine as devel-stage
WORKDIR /app
COPY package*.json /app/
COPY . /app/
RUN mkdir /tmp/node_modules && ln -s /tmp/node_modules /app/node_modules

# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app/
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
