apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cooking-assistant-pgsql
  namespace: __NAMESPACE__
  labels:
    app: cooking-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cooking-assistant-rabbitmq
  namespace: __NAMESPACE__
  labels:
    app: cooking-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph
