# Generated by Django 2.1.3 on 2019-02-27 13:54

from django.contrib.postgres.operations import (
    TrigramExtension,
    UnaccentExtension,
)
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.RunSQL('CREATE TEXT SEARCH CONFIGURATION french_unaccent( COPY = french )'),
        migrations.RunSQL('ALTER TEXT SEARCH CONFIGURATION french_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem'),
    ]
